[package]
name = "colore_ai_neuroflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neuroflow = "0.2.0"
httparse = "1.8.0"
